"""Shared configuration registry and resolution utilities."""

from .registry import (
    FieldMetadata,
    flatten,
    unflatten,
    build_registry,
    get_default_config_dict,
)
from .resolver import ResolvedConfig, resolve_effective_config
from .persistence import (
    CONFIG_SCHEMA_VERSION,
    apply_project_config_to_live_facade,
    compute_config_hash,
    get_project_config_path,
    get_draft_override_path,
    get_run_override_path,
    get_run_effective_path,
    load_project_config,
    save_project_config,
    load_draft_override,
    save_draft_override,
    clear_draft_override,
    load_run_override,
    save_run_override,
    load_run_effective,
    save_run_effective,
)
from .validation import ValidationError, validate_config
from .gui_support import (
    COMMON_SETTINGS_SCHEMA,
    CommonSettingField,
    list_runtime_profile_targets,
    list_supported_profile_target_ids,
)
from .profile_target_adapter import (
    ProfileTargetAdapter,
    get_profile_target_adapter,
    iter_all_profile_target_adapters,
    iter_runtime_profile_target_adapters,
    strip_activation_keys_from_flat_map,
    strip_activation_keys_from_nested_map,
)

__all__ = [
    "FieldMetadata",
    "ResolvedConfig",
    "ValidationError",
    "CONFIG_SCHEMA_VERSION",
    "apply_project_config_to_live_facade",
    "build_registry",
    "clear_draft_override",
    "compute_config_hash",
    "flatten",
    "get_default_config_dict",
    "get_draft_override_path",
    "get_project_config_path",
    "get_run_effective_path",
    "get_run_override_path",
    "load_draft_override",
    "load_project_config",
    "load_run_effective",
    "load_run_override",
    "resolve_effective_config",
    "save_draft_override",
    "save_project_config",
    "save_run_effective",
    "save_run_override",
    "unflatten",
    "validate_config",
    "COMMON_SETTINGS_SCHEMA",
    "CommonSettingField",
    "list_runtime_profile_targets",
    "list_supported_profile_target_ids",
    "ProfileTargetAdapter",
    "get_profile_target_adapter",
    "iter_all_profile_target_adapters",
    "iter_runtime_profile_target_adapters",
    "strip_activation_keys_from_flat_map",
    "strip_activation_keys_from_nested_map",
]
