"""Declarative specs for module registry metadata and lazy import map."""

from __future__ import annotations

from typing import Dict, List

from transcriptx.core.domain.module_requirements import Enhancement, Requirement

EXTRA_REPRESENTATIVE: Dict[str, str] = {
    "voice": "opensmile",
    "emotion": "transformers",
    "nlp": "spacy",
    "ner": "spacy",
    "bertopic": "bertopic",
    "maps": "folium",
    "visualization": "matplotlib",
    "plotly": "plotly",
}

MODULE_CLASS_MAP: Dict[str, tuple[str, str]] = {
    "corrections": ("transcriptx.core.analysis.corrections", "CorrectionsAnalysis"),
    "emotion": ("transcriptx.core.analysis.emotion", "EmotionAnalysis"),
    "contagion": ("transcriptx.core.analysis.contagion", "ContagionAnalysis"),
    "sentiment": ("transcriptx.core.analysis.sentiment", "SentimentAnalysis"),
    "acts": ("transcriptx.core.analysis.acts.analysis", "ActsAnalysis"),
    "stats": ("transcriptx.core.analysis.stats", "StatsAnalysis"),
    "interactions": (
        "transcriptx.core.analysis.interactions.analysis",
        "InteractionsAnalysis",
    ),
    "ner": ("transcriptx.core.analysis.ner", "NERAnalysis"),
    "entity_sentiment": (
        "transcriptx.core.analysis.entity_sentiment",
        "EntitySentimentAnalysis",
    ),
    "affect_tension": (
        "transcriptx.core.analysis.affect_tension",
        "AffectTensionAnalysis",
    ),
    "conversation_loops": (
        "transcriptx.core.analysis.conversation_loops.analysis",
        "ConversationLoopsAnalysis",
    ),
    "topic_modeling": (
        "transcriptx.core.analysis.topic_modeling",
        "TopicModelingAnalysis",
    ),
    "semantic_similarity": (
        "transcriptx.core.analysis.semantic_similarity",
        "SemanticSimilarityAnalysis",
    ),
    "semantic_similarity_advanced": (
        "transcriptx.core.analysis.semantic_similarity",
        "SemanticSimilarityAdvancedAnalysis",
    ),
    "semantic_similarity_v2": (
        "transcriptx.core.analysis.semantic_similarity_v2",
        "SemanticSimilarityV2Analysis",
    ),
    "transcript_output": (
        "transcriptx.core.analysis.transcript_output",
        "TranscriptOutputAnalysis",
    ),
    "simplified_transcript": (
        "transcriptx.core.analysis.simplified_transcript",
        "SimplifiedTranscriptAnalysis",
    ),
    "wordclouds": (
        "transcriptx.core.analysis.wordclouds.analysis",
        "WordcloudsAnalysis",
    ),
    "tics": ("transcriptx.core.analysis.tics", "TicsAnalysis"),
    "insight_eligibility": (
        "transcriptx.core.analysis.insight_eligibility",
        "InsightEligibilityAnalysis",
    ),
    "understandability": (
        "transcriptx.core.analysis.understandability",
        "UnderstandabilityAnalysis",
    ),
    "temporal_dynamics": (
        "transcriptx.core.analysis.temporal_dynamics.analysis",
        "TemporalDynamicsAnalysis",
    ),
    "qa_analysis": ("transcriptx.core.analysis.qa_analysis.analysis", "QAAnalysis"),
    "pauses": ("transcriptx.core.analysis.dynamics.pauses", "PausesAnalysis"),
    "echoes": ("transcriptx.core.analysis.dynamics.echoes", "EchoesAnalysis"),
    "momentum": ("transcriptx.core.analysis.dynamics.momentum", "MomentumAnalysis"),
    "moments": ("transcriptx.core.analysis.dynamics.moments", "MomentsAnalysis"),
    "highlights": ("transcriptx.core.analysis.highlights", "HighlightsAnalysis"),
    "summary": ("transcriptx.core.analysis.summary", "SummaryAnalysis"),
    "narrative_summary": (
        "transcriptx.core.analysis.narrative_summary",
        "NarrativeSummaryAnalysis",
    ),
    "llm_summary": (
        "transcriptx.core.analysis.llm_summary",
        "LLMSummaryAnalysis",
    ),
    "insights": ("transcriptx.core.analysis.insights", "InsightsAnalysis"),
    "voice_features": (
        "transcriptx.core.analysis.voice_features",
        "VoiceFeaturesAnalysis",
    ),
    "voice_mismatch": (
        "transcriptx.core.analysis.voice_mismatch",
        "VoiceMismatchAnalysis",
    ),
    "voice_tension": (
        "transcriptx.core.analysis.voice_tension",
        "VoiceTensionAnalysis",
    ),
    "voice_fingerprint": (
        "transcriptx.core.analysis.voice_fingerprint",
        "VoiceFingerprintAnalysis",
    ),
    "prosody_dashboard": (
        "transcriptx.core.analysis.voice.dashboard",
        "ProsodyDashboardAnalysis",
    ),
    "voice_charts_core": (
        "transcriptx.core.analysis.voice.charts_core",
        "VoiceChartsCoreAnalysis",
    ),
    "voice_contours": (
        "transcriptx.core.analysis.voice.contours",
        "VoiceContoursAnalysis",
    ),
}


def build_module_definitions(
    default_requirements: List[Requirement],
) -> Dict[str, Dict]:
    """Return declarative module metadata definitions."""
    return {
        "corrections": {
            "description": "Semi-automatic transcription accuracy tuning",
            "dependencies": [],
            "category": "light",
            "determinism_tier": "T0",
            "requirements": [Requirement.SEGMENTS],
            "enhancements": [],
            "exclude_from_default": True,
            "post_processing_only": True,
        },
        "acts": {
            "description": "Dialogue Act Classification",
            "dependencies": [],
            "category": "medium",
            "determinism_tier": "T0",
            "requirements": [Requirement.SEGMENTS, Requirement.SPEAKER_LABELS],
            "enhancements": [],
        },
        "conversation_loops": {
            "description": "Conversation Loop Detection",
            "dependencies": [],
            "category": "light",
            "determinism_tier": "T0",
            "requirements": [Requirement.SEGMENTS, Requirement.SPEAKER_LABELS],
            "enhancements": [],
            "requires_multiple_speakers": True,
        },
        "contagion": {
            "description": "Emotional Contagion Detection",
            "dependencies": ["emotion"],
            "category": "heavy",
            "determinism_tier": "T1",
            "requirements": [Requirement.SEGMENTS, Requirement.SPEAKER_LABELS],
            "enhancements": [],
            "requires_multiple_speakers": True,
            "required_extras": ["emotion"],
        },
        "emotion": {
            "description": "Emotion Analysis",
            "dependencies": [],
            "category": "medium",
            "determinism_tier": "T1",
            "requirements": [Requirement.SEGMENTS, Requirement.SPEAKER_LABELS],
            "enhancements": [],
        },
        "entity_sentiment": {
            "description": "Entity-based Sentiment Analysis",
            "dependencies": ["ner", "sentiment"],
            "category": "heavy",
            "determinism_tier": "T1",
            "requirements": [Requirement.SEGMENTS, Requirement.SPEAKER_LABELS],
            "enhancements": [],
            "required_extras": ["nlp"],
        },
        "affect_tension": {
            "description": "Emotion + Sentiment mismatch and tension indices",
            "dependencies": ["emotion", "sentiment"],
            "category": "medium",
            "determinism_tier": "T1",
            "requirements": [Requirement.SEGMENTS, Requirement.SPEAKER_LABELS],
            "enhancements": [],
            "required_extras": ["emotion"],
        },
        "interactions": {
            "description": "Speaker Interaction Analysis",
            "dependencies": [],
            "category": "medium",
            "determinism_tier": "T0",
            "requirements": [Requirement.SEGMENTS, Requirement.SPEAKER_LABELS],
            "enhancements": [],
            "requires_multiple_speakers": True,
        },
        "ner": {
            "description": "Named Entity Recognition",
            "dependencies": [],
            "category": "medium",
            "determinism_tier": "T1",
            "requirements": default_requirements,
            "enhancements": [],
            "required_extras": ["nlp"],
        },
        "semantic_similarity": {
            "description": "Semantic Similarity Analysis (Legacy)",
            "dependencies": [],
            "category": "heavy",
            "determinism_tier": "T1",
            "requirements": default_requirements,
            "enhancements": [],
            "requires_multiple_speakers": True,
            "legacy": True,
        },
        "semantic_similarity_advanced": {
            "description": "Advanced Semantic Similarity with Analysis Integration (Legacy)",
            "dependencies": [],
            "category": "heavy",
            "determinism_tier": "T1",
            "requirements": default_requirements,
            "enhancements": [],
            "requires_multiple_speakers": True,
            "legacy": True,
        },
        "semantic_similarity_v2": {
            "description": "Semantic similarity v2 (batched embeddings, vectorized similarity)",
            "dependencies": [],
            "category": "heavy",
            "determinism_tier": "T1",
            "requirements": default_requirements,
            "enhancements": [],
            "requires_multiple_speakers": True,
        },
        "sentiment": {
            "description": "Sentiment Analysis",
            "dependencies": [],
            "category": "medium",
            "determinism_tier": "T1",
            "requirements": [Requirement.SEGMENTS, Requirement.SPEAKER_LABELS],
            "enhancements": [],
        },
        "stats": {
            "description": "Statistical Analysis",
            "dependencies": [],
            "category": "light",
            "determinism_tier": "T0",
            "requirements": [Requirement.SEGMENTS, Requirement.SPEAKER_LABELS],
            "enhancements": [],
        },
        "topic_modeling": {
            "description": "Topic Modeling",
            "dependencies": ["insight_eligibility"],
            "category": "heavy",
            "determinism_tier": "T2",
            "requirements": default_requirements,
            "enhancements": [],
        },
        "transcript_output": {
            "description": "Generate human readable transcripts",
            "dependencies": [],
            "category": "light",
            "determinism_tier": "T0",
            "requirements": default_requirements,
            "enhancements": [Enhancement.SPEAKER_DISPLAY_NAMES],
        },
        "simplified_transcript": {
            "description": "Simplified transcript (tics, agreements, repetitions removed)",
            "dependencies": [],
            "category": "light",
            "determinism_tier": "T0",
            "requirements": [Requirement.SEGMENTS, Requirement.SPEAKER_LABELS],
            "enhancements": [],
        },
        "understandability": {
            "description": "Understandability Analysis",
            "dependencies": [],
            "category": "medium",
            "determinism_tier": "T0",
            "requirements": [Requirement.SEGMENTS, Requirement.SPEAKER_LABELS],
            "enhancements": [],
            "gate_on_turn_taking_speakers": True,
        },
        "wordclouds": {
            "description": "Word Cloud Generation",
            "dependencies": ["insight_eligibility"],
            "category": "light",
            "determinism_tier": "T1",
            "requirements": default_requirements,
            "enhancements": [],
        },
        "tics": {
            "description": "Verbal Tics Analysis",
            "dependencies": [],
            "category": "light",
            "determinism_tier": "T0",
            "requirements": [Requirement.SEGMENTS, Requirement.SPEAKER_LABELS],
            "enhancements": [],
        },
        "insight_eligibility": {
            "description": "Shared content-vs-style insight eligibility pipeline",
            "dependencies": ["tics"],
            "category": "light",
            "determinism_tier": "T0",
            "requirements": [Requirement.SEGMENTS, Requirement.SPEAKER_LABELS],
            "enhancements": [],
        },
        "temporal_dynamics": {
            "description": "Temporal Dynamics Analysis",
            "dependencies": [],
            "category": "medium",
            "determinism_tier": "T1",
            "requirements": [
                Requirement.SEGMENTS,
                Requirement.SEGMENT_TIMESTAMPS,
                Requirement.SPEAKER_LABELS,
            ],
            "enhancements": [],
        },
        "qa_analysis": {
            "description": "Question-Answer Pairing and Response Quality",
            "dependencies": ["acts"],
            "category": "medium",
            "determinism_tier": "T1",
            "requirements": [Requirement.SEGMENTS, Requirement.SPEAKER_LABELS],
            "enhancements": [],
            "requires_multiple_speakers": True,
        },
        "pauses": {
            "description": "Silence and Timing Analysis",
            "dependencies": [],
            "category": "light",
            "determinism_tier": "T0",
            "requirements": [
                Requirement.SEGMENTS,
                Requirement.SEGMENT_TIMESTAMPS,
                Requirement.SPEAKER_LABELS,
            ],
            "enhancements": [],
        },
        "echoes": {
            "description": "Quote/Echo/Paraphrase Detection",
            "dependencies": [],
            "category": "medium",
            "determinism_tier": "T1",
            "requirements": [Requirement.SEGMENTS, Requirement.SPEAKER_LABELS],
            "enhancements": [],
            "requires_multiple_speakers": True,
            "gate_on_turn_taking_speakers": True,
        },
        "momentum": {
            "description": "Stall/Flow Index Analysis",
            "dependencies": ["pauses"],
            "category": "medium",
            "determinism_tier": "T0",
            "requirements": [
                Requirement.SEGMENTS,
                Requirement.SEGMENT_TIMESTAMPS,
                Requirement.SPEAKER_LABELS,
            ],
            "enhancements": [],
        },
        "moments": {
            "description": "Ranked Moments Worth Revisiting",
            "dependencies": ["momentum"],
            "category": "light",
            "determinism_tier": "T0",
            "requirements": [Requirement.SEGMENTS, Requirement.SEGMENT_TIMESTAMPS],
            "enhancements": [],
        },
        "highlights": {
            "description": "Highlights and conflict moments (quote-forward)",
            "dependencies": ["insight_eligibility"],
            "category": "light",
            "determinism_tier": "T0",
            "requirements": [
                Requirement.SEGMENTS,
                Requirement.SEGMENT_TIMESTAMPS,
                Requirement.SPEAKER_LABELS,
            ],
            "enhancements": [],
        },
        "summary": {
            "description": "Executive brief summary derived from highlights",
            "dependencies": ["highlights"],
            "category": "light",
            "determinism_tier": "T0",
            "requirements": [
                Requirement.SEGMENTS,
                Requirement.SEGMENT_TIMESTAMPS,
                Requirement.SPEAKER_LABELS,
            ],
            "enhancements": [],
        },
        "narrative_summary": {
            "description": "Grounded executive narrative from deterministic summary (LLM)",
            "dependencies": ["summary"],
            "category": "medium",
            "determinism_tier": "T2",
            "requirements": [
                Requirement.SEGMENTS,
                Requirement.SEGMENT_TIMESTAMPS,
                Requirement.SPEAKER_LABELS,
            ],
            "enhancements": [],
            "requires_llm": True,
        },
        "llm_summary": {
            "description": "Abstractive transcript summary via local LLM",
            "dependencies": [],
            "category": "medium",
            "determinism_tier": "T2",
            "requirements": [Requirement.SEGMENTS],
            "enhancements": [],
            "requires_llm": True,
        },
        "insights": {
            "description": "Content-first insights layer separated from style markers",
            "dependencies": ["insight_eligibility", "highlights", "topic_modeling"],
            "category": "light",
            "determinism_tier": "T0",
            "requirements": [
                Requirement.SEGMENTS,
                Requirement.SEGMENT_TIMESTAMPS,
                Requirement.SPEAKER_LABELS,
            ],
            "enhancements": [],
        },
        "voice_features": {
            "description": "Voice feature extraction and caching",
            "dependencies": [],
            "category": "heavy",
            "determinism_tier": "T0",
            "requirements": [
                Requirement.SEGMENTS,
                Requirement.SEGMENT_TIMESTAMPS,
                Requirement.SPEAKER_LABELS,
            ],
            "enhancements": [],
            "requires_audio": True,
            "supports_audio": True,
            "cost_tier": "heavy",
            "required_extras": ["voice"],
        },
        "voice_mismatch": {
            "description": "Tone–Text mismatch detection (sarcasm/discord moments)",
            "dependencies": ["voice_features"],
            "category": "medium",
            "determinism_tier": "T0",
            "requirements": [
                Requirement.SEGMENTS,
                Requirement.SEGMENT_TIMESTAMPS,
                Requirement.SPEAKER_LABELS,
            ],
            "enhancements": [],
            "exclude_from_default": True,
            "requires_audio": True,
            "supports_audio": True,
            "cost_tier": "normal",
            "required_extras": ["voice"],
        },
        "voice_tension": {
            "description": "Conversation tension curve from voice",
            "dependencies": ["voice_features"],
            "category": "medium",
            "determinism_tier": "T0",
            "requirements": [Requirement.SEGMENTS, Requirement.SEGMENT_TIMESTAMPS],
            "enhancements": [],
            "exclude_from_default": True,
            "requires_audio": True,
            "supports_audio": True,
            "cost_tier": "normal",
            "required_extras": ["voice"],
        },
        "voice_fingerprint": {
            "description": "Per-speaker voice fingerprint baseline and drift",
            "dependencies": ["voice_features"],
            "category": "medium",
            "determinism_tier": "T0",
            "requirements": [
                Requirement.SEGMENTS,
                Requirement.SEGMENT_TIMESTAMPS,
                Requirement.SPEAKER_LABELS,
            ],
            "enhancements": [],
            "exclude_from_default": True,
            "requires_audio": True,
            "supports_audio": True,
            "cost_tier": "normal",
            "required_extras": ["voice"],
        },
        "prosody_dashboard": {
            "description": "Prosody dashboard charts from voice features",
            "dependencies": ["voice_features"],
            "category": "medium",
            "determinism_tier": "T0",
            "requirements": [
                Requirement.SEGMENTS,
                Requirement.SEGMENT_TIMESTAMPS,
                Requirement.SPEAKER_LABELS,
            ],
            "enhancements": [],
            "requires_audio": True,
            "supports_audio": True,
            "cost_tier": "cheap",
            "required_extras": ["voice"],
        },
        "voice_charts_core": {
            "description": "Voice charts core: pauses + rhythm indices",
            "dependencies": ["voice_features"],
            "category": "medium",
            "determinism_tier": "T0",
            "requirements": [
                Requirement.SEGMENTS,
                Requirement.SEGMENT_TIMESTAMPS,
                Requirement.SPEAKER_LABELS,
            ],
            "enhancements": [],
            "requires_audio": True,
            "supports_audio": True,
            "output_namespace": "voice",
            "output_version": "v1",
            "cost_tier": "normal",
            "required_extras": ["voice"],
        },
        "voice_contours": {
            "description": "Voice contours (slow; needs audio decode + pitch tracking)",
            "dependencies": ["voice_features"],
            "category": "medium",
            "determinism_tier": "T0",
            "requirements": [
                Requirement.SEGMENTS,
                Requirement.SEGMENT_TIMESTAMPS,
                Requirement.SPEAKER_LABELS,
            ],
            "enhancements": [],
            "requires_audio": True,
            "supports_audio": True,
            "exclude_from_default": True,
            "supports_group": False,
            "output_namespace": "voice",
            "output_version": "v1",
            "cost_tier": "heavy",
            "required_extras": ["voice"],
        },
    }
