"""Initial migration

Revision ID: fab8f2c33c2d
Revises: 0001_canonical_models
Create Date: 2026-01-30 23:14:13.764009
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

revision = 'fab8f2c33c2d'
down_revision = '0001_canonical_models'
branch_labels = None
depends_on = None


def _has_index(table_name: str, index_name: str) -> bool:
    bind = op.get_bind()
    if not inspect(bind).has_table(table_name):
        return False
    indexes = inspect(bind).get_indexes(table_name)
    return any(idx["name"] == index_name for idx in indexes)


def _has_fk(table_name: str, *column_names: str) -> bool:
    bind = op.get_bind()
    if not inspect(bind).has_table(table_name):
        return False
    fks = inspect(bind).get_foreign_keys(table_name)
    for fk in fks:
        if set(fk["constrained_columns"]) >= set(column_names):
            return True
    return False


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # performance_spans indexes (SQLite: plain column names, no DESC)
    if _has_index('performance_spans', 'idx_span_name_start_time'):
        op.drop_index(op.f('idx_span_name_start_time'), table_name='performance_spans')
    if not _has_index('performance_spans', 'idx_span_name_start_time'):
        op.create_index('idx_span_name_start_time', 'performance_spans', ['name', 'start_time'], unique=False)
    if _has_index('performance_spans', 'idx_span_start_time'):
        op.drop_index(op.f('idx_span_start_time'), table_name='performance_spans')
    if not _has_index('performance_spans', 'idx_span_start_time'):
        op.create_index('idx_span_start_time', 'performance_spans', ['start_time'], unique=False)

    if not _has_index('speakers', 'ix_speakers_first_name'):
        op.create_index(op.f('ix_speakers_first_name'), 'speakers', ['first_name'], unique=False)
    if not _has_index('speakers', 'ix_speakers_surname'):
        op.create_index(op.f('ix_speakers_surname'), 'speakers', ['surname'], unique=False)

    _tf_drop = ('idx_transcript_content_hash', 'idx_transcript_schema_version',
                'idx_transcript_sentence_schema_version', 'idx_transcript_source_hash')
    for idx in _tf_drop:
        if _has_index('transcript_files', idx):
            op.drop_index(op.f(idx), table_name='transcript_files')
    _tf_create = (
        ('ix_transcript_files_schema_version', 'schema_version'),
        ('ix_transcript_files_sentence_schema_version', 'sentence_schema_version'),
        ('ix_transcript_files_source_hash', 'source_hash'),
        ('ix_transcript_files_transcript_content_hash', 'transcript_content_hash'),
    )
    for ix_name, col in _tf_create:
        if not _has_index('transcript_files', ix_name):
            op.create_index(op.f(ix_name), 'transcript_files', [col], unique=False)

    if not _has_index('transcript_segments', 'ix_transcript_segments_transcript_speaker_id'):
        op.create_index(op.f('ix_transcript_segments_transcript_speaker_id'), 'transcript_segments', ['transcript_speaker_id'], unique=False)
    if not _has_fk('transcript_segments', 'transcript_speaker_id'):
        with op.batch_alter_table('transcript_segments') as batch:
            batch.create_foreign_key('fk_transcript_segments_transcript_speaker_id', 'transcript_speakers', ['transcript_speaker_id'], ['id'], ondelete='SET NULL')
    if not _has_index('transcript_sentences', 'ix_transcript_sentences_transcript_speaker_id'):
        op.create_index(op.f('ix_transcript_sentences_transcript_speaker_id'), 'transcript_sentences', ['transcript_speaker_id'], unique=False)
    if not _has_fk('transcript_sentences', 'transcript_speaker_id'):
        with op.batch_alter_table('transcript_sentences') as batch:
            batch.create_foreign_key('fk_transcript_sentences_transcript_speaker_id', 'transcript_speakers', ['transcript_speaker_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcript_sentences') as batch:
        batch.drop_constraint('fk_transcript_sentences_transcript_speaker_id', type_='foreignkey')
    op.drop_index(op.f('ix_transcript_sentences_transcript_speaker_id'), table_name='transcript_sentences')
    with op.batch_alter_table('transcript_segments') as batch:
        batch.drop_constraint('fk_transcript_segments_transcript_speaker_id', type_='foreignkey')
    op.drop_index(op.f('ix_transcript_segments_transcript_speaker_id'), table_name='transcript_segments')
    op.drop_index(op.f('ix_transcript_files_transcript_content_hash'), table_name='transcript_files')
    op.drop_index(op.f('ix_transcript_files_source_hash'), table_name='transcript_files')
    op.drop_index(op.f('ix_transcript_files_sentence_schema_version'), table_name='transcript_files')
    op.drop_index(op.f('ix_transcript_files_schema_version'), table_name='transcript_files')
    op.create_index(op.f('idx_transcript_source_hash'), 'transcript_files', ['source_hash'], unique=False)
    op.create_index(op.f('idx_transcript_sentence_schema_version'), 'transcript_files', ['sentence_schema_version'], unique=False)
    op.create_index(op.f('idx_transcript_schema_version'), 'transcript_files', ['schema_version'], unique=False)
    op.create_index(op.f('idx_transcript_content_hash'), 'transcript_files', ['transcript_content_hash'], unique=False)
    op.drop_index(op.f('ix_speakers_surname'), table_name='speakers')
    op.drop_index(op.f('ix_speakers_first_name'), table_name='speakers')
    op.drop_index('idx_span_start_time', table_name='performance_spans')
    op.create_index(op.f('idx_span_start_time'), 'performance_spans', ['start_time'], unique=False)
    op.drop_index('idx_span_name_start_time', table_name='performance_spans')
    op.create_index(op.f('idx_span_name_start_time'), 'performance_spans', ['name', 'start_time'], unique=False)
    # ### end Alembic commands ###
