"""Initial migration

Revision ID: fab8f2c33c2d
Revises: 0001_canonical_models
Create Date: 2026-01-30 23:14:13.764009
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = 'fab8f2c33c2d'
down_revision = '0001_canonical_models'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_span_name_start_time'), table_name='performance_spans')
    op.create_index('idx_span_name_start_time', 'performance_spans', ['name', sa.literal_column('start_time DESC')], unique=False)
    op.drop_index(op.f('idx_span_start_time'), table_name='performance_spans')
    op.create_index('idx_span_start_time', 'performance_spans', [sa.literal_column('start_time DESC')], unique=False)
    op.create_index(op.f('ix_speakers_first_name'), 'speakers', ['first_name'], unique=False)
    op.create_index(op.f('ix_speakers_surname'), 'speakers', ['surname'], unique=False)
    op.drop_index(op.f('idx_transcript_content_hash'), table_name='transcript_files')
    op.drop_index(op.f('idx_transcript_schema_version'), table_name='transcript_files')
    op.drop_index(op.f('idx_transcript_sentence_schema_version'), table_name='transcript_files')
    op.drop_index(op.f('idx_transcript_source_hash'), table_name='transcript_files')
    op.create_index(op.f('ix_transcript_files_schema_version'), 'transcript_files', ['schema_version'], unique=False)
    op.create_index(op.f('ix_transcript_files_sentence_schema_version'), 'transcript_files', ['sentence_schema_version'], unique=False)
    op.create_index(op.f('ix_transcript_files_source_hash'), 'transcript_files', ['source_hash'], unique=False)
    op.create_index(op.f('ix_transcript_files_transcript_content_hash'), 'transcript_files', ['transcript_content_hash'], unique=False)
    op.create_index(op.f('ix_transcript_segments_transcript_speaker_id'), 'transcript_segments', ['transcript_speaker_id'], unique=False)
    op.create_foreign_key(None, 'transcript_segments', 'transcript_speakers', ['transcript_speaker_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_transcript_sentences_transcript_speaker_id'), 'transcript_sentences', ['transcript_speaker_id'], unique=False)
    op.create_foreign_key(None, 'transcript_sentences', 'transcript_speakers', ['transcript_speaker_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transcript_sentences', type_='foreignkey')
    op.drop_index(op.f('ix_transcript_sentences_transcript_speaker_id'), table_name='transcript_sentences')
    op.drop_constraint(None, 'transcript_segments', type_='foreignkey')
    op.drop_index(op.f('ix_transcript_segments_transcript_speaker_id'), table_name='transcript_segments')
    op.drop_index(op.f('ix_transcript_files_transcript_content_hash'), table_name='transcript_files')
    op.drop_index(op.f('ix_transcript_files_source_hash'), table_name='transcript_files')
    op.drop_index(op.f('ix_transcript_files_sentence_schema_version'), table_name='transcript_files')
    op.drop_index(op.f('ix_transcript_files_schema_version'), table_name='transcript_files')
    op.create_index(op.f('idx_transcript_source_hash'), 'transcript_files', ['source_hash'], unique=False)
    op.create_index(op.f('idx_transcript_sentence_schema_version'), 'transcript_files', ['sentence_schema_version'], unique=False)
    op.create_index(op.f('idx_transcript_schema_version'), 'transcript_files', ['schema_version'], unique=False)
    op.create_index(op.f('idx_transcript_content_hash'), 'transcript_files', ['transcript_content_hash'], unique=False)
    op.drop_index(op.f('ix_speakers_surname'), table_name='speakers')
    op.drop_index(op.f('ix_speakers_first_name'), table_name='speakers')
    op.drop_index('idx_span_start_time', table_name='performance_spans')
    op.create_index(op.f('idx_span_start_time'), 'performance_spans', ['start_time'], unique=False)
    op.drop_index('idx_span_name_start_time', table_name='performance_spans')
    op.create_index(op.f('idx_span_name_start_time'), 'performance_spans', ['name', 'start_time'], unique=False)
    # ### end Alembic commands ###
