"""Tests for report renderer (report.md and report.txt)."""

from __future__ import annotations


from transcriptx.core.analysis.stats.report_renderer import (
    SECTION_ORDER,
    md_to_txt,
    render_report_md,
)


def _minimal_report_payload() -> dict:
    return {
        "meta": {
            "base_name": "sample",
            "generated_at": "2026-03-17T12:00:00Z",
            "run_id": "run_123",
        },
        "overview": {
            "total_duration_sec": 120.5,
            "total_words": 1500,
            "speaker_count_named": 2,
        },
        "modules": {},
        "report_summary_index": [],
        "speakers": [],
        "warnings": [],
    }


def test_render_report_md_minimal_payload() -> None:
    payload = _minimal_report_payload()
    md = render_report_md(payload)
    assert "# Report: sample" in md
    assert "Generated: 2026-03-17" in md
    assert "Run ID: run_123" in md
    assert "120s" in md or "121s" in md
    assert "1500" in md
    assert "Speaker breakdown" not in md  # no speakers
    assert "## Warnings" not in md  # no warnings
    assert "manifest.json" in md
    assert "No data available" not in md


def test_render_report_md_includes_footer() -> None:
    payload = _minimal_report_payload()
    md = render_report_md(payload)
    assert "---" in md
    assert "Generated by TranscriptX" in md
    assert "Run ID: run_123" in md
    assert md.endswith("\n")


def test_render_report_md_speakers_section_when_present() -> None:
    payload = _minimal_report_payload()
    payload["speakers"] = [
        {
            "name": "Alice",
            "words": 900,
            "pct_total_words": 0.6,
            "duration_hhmmss": "01:30",
            "words_per_min": 60.0,
        },
        {
            "name": "Bob",
            "words": 600,
            "pct_total_words": 0.4,
            "duration_hhmmss": "01:00",
            "words_per_min": 60.0,
        },
    ]
    md = render_report_md(payload)
    assert "## Speaker breakdown" in md
    assert "**Alice**" in md
    assert "900 words" in md
    assert "60%" in md
    assert "**Bob**" in md
    assert "600 words" in md


def test_render_report_md_full_section_from_report_summary_index() -> None:
    payload = _minimal_report_payload()
    payload["report_summary_index"] = [
        {
            "section_name": "Sentiment",
            "descriptor": "Tone",
            "source_modules": ["sentiment"],
        },
    ]
    payload["modules"] = {
        "sentiment": {
            "module_status": "ran",
            "report_contribution_status": "full_section",
            "section_payload": {"mean_compound": 0.35},
        },
    }
    md = render_report_md(payload)
    assert "## Sentiment" in md
    assert "Mean compound sentiment: 0.350" in md


def test_render_report_md_mention_only_in_additional_outputs() -> None:
    payload = _minimal_report_payload()
    payload["modules"] = {
        "tics": {
            "module_status": "ran",
            "report_contribution_status": "mention_only",
            "reason": "failed minimum viable contract",
        },
    }
    md = render_report_md(payload)
    assert "## Additional outputs available" in md
    assert "tics" in md
    assert "The following modules produced outputs" in md


def test_render_report_md_warnings_section() -> None:
    payload = _minimal_report_payload()
    payload["warnings"] = [
        "sentiment: expected summary at sentiment/data/global/sample_sentiment_summary.json, not found or invalid (file missing)",
    ]
    md = render_report_md(payload)
    assert "## Warnings" in md
    assert "sentiment" in md
    assert "not found or invalid" in md


def test_render_report_md_stable_order_no_placeholder_text() -> None:
    payload = _minimal_report_payload()
    payload["report_summary_index"] = [
        {
            "section_name": "Named entities",
            "descriptor": "Entities",
            "source_modules": ["ner"],
        },
        {
            "section_name": "Sentiment",
            "descriptor": "Tone",
            "source_modules": ["sentiment"],
        },
    ]
    payload["modules"] = {
        "ner": {
            "module_status": "ran",
            "report_contribution_status": "full_section",
            "section_payload": {"entities": [{"text": "Alice", "label": "PERSON"}]},
        },
        "sentiment": {
            "module_status": "ran",
            "report_contribution_status": "full_section",
            "section_payload": {"mean_compound": 0.1},
        },
    }
    md = render_report_md(payload)
    # Sentiment comes before ner in SECTION_ORDER, so Sentiment section should appear before Named entities
    pos_sentiment = md.find("## Sentiment")
    pos_ner = md.find("## Named entities")
    assert pos_sentiment != -1
    assert pos_ner != -1
    assert pos_sentiment < pos_ner
    assert "No data available" not in md


def test_render_report_md_summary_section_brief() -> None:
    payload = _minimal_report_payload()
    payload["report_summary_index"] = [
        {
            "section_name": "Executive summary",
            "descriptor": "Brief",
            "source_modules": ["summary"],
        },
    ]
    payload["modules"] = {
        "summary": {
            "module_status": "ran",
            "report_contribution_status": "full_section",
            "section_payload": {"brief": "The meeting focused on Q1 goals."},
        },
    }
    md = render_report_md(payload)
    assert "## Executive summary" in md
    assert "The meeting focused on Q1 goals." in md


def test_md_to_txt_empty() -> None:
    assert md_to_txt("") == ""
    assert md_to_txt("   ") == "\n"


def test_md_to_txt_headers_converted() -> None:
    md = "# Title\n\nBody"
    txt = md_to_txt(md)
    assert "Title" in txt
    assert "=" in txt
    assert "#" not in txt or "Title" in txt
    md2 = "## Section 2\n\nContent"
    txt2 = md_to_txt(md2)
    assert "Section 2" in txt2
    assert "-" in txt2


def test_md_to_txt_bold_stripped() -> None:
    md = "Hello **world** and __again__."
    txt = md_to_txt(md)
    assert "world" in txt
    assert "again" in txt
    assert "**" not in txt
    assert "__" not in txt


def test_md_to_txt_normalizes_newlines() -> None:
    md = "Line 1\n\n\n\n\nLine 2"
    txt = md_to_txt(md)
    assert "\n\n\n" not in txt
    assert "Line 1" in txt
    assert "Line 2" in txt


def test_md_to_txt_roundtrip_preserves_content() -> None:
    payload = _minimal_report_payload()
    payload["speakers"] = [
        {
            "name": "A",
            "words": 10,
            "pct_total_words": 1.0,
            "duration_hhmmss": "0:00",
            "words_per_min": 0.0,
        }
    ]
    md = render_report_md(payload)
    txt = md_to_txt(md)
    assert "Report: sample" in txt
    assert "A" in txt
    assert "10" in txt


def test_section_order_constant() -> None:
    assert SECTION_ORDER[0] == "header"
    assert "speakers" in SECTION_ORDER
    assert "footer" in SECTION_ORDER
    assert SECTION_ORDER.index("sentiment") < SECTION_ORDER.index("emotion")
    assert "additional_outputs" in SECTION_ORDER
    assert "warnings" in SECTION_ORDER
