"""Stable error codes for group LLM synthesis."""

from __future__ import annotations

# Collect / validation
MISSING_COLLECT_ARTIFACT = "MISSING_COLLECT_ARTIFACT"
COLLECT_SCHEMA_MISMATCH = "COLLECT_SCHEMA_MISMATCH"
INVALID_COLLECT_PAYLOAD = "INVALID_COLLECT_PAYLOAD"
NO_USABLE_MEMBER_SUMMARIES = "NO_USABLE_MEMBER_SUMMARIES"
DUPLICATE_ORDER_INDEX = "DUPLICATE_ORDER_INDEX"

# Config / gate
LLM_CONFIGURATION = "LLM_CONFIGURATION"
LLM_DISABLED = "LLM_DISABLED"
SYNTHESIS_DISABLED = "SYNTHESIS_DISABLED"
SYNTHESIS_LOCK_TIMEOUT = "SYNTHESIS_LOCK_TIMEOUT"

# Runtime
PROMPT_BUDGET = "PROMPT_BUDGET"
SUMMARY_OVERSIZED = "SUMMARY_OVERSIZED"
LLM_UNAVAILABLE = "LLM_UNAVAILABLE"
LLM_INVALID_RESPONSE = "LLM_INVALID_RESPONSE"
MAX_SPEAKERS = "MAX_SPEAKERS"
CANCELLED = "CANCELLED"
UNEXPECTED_ERROR = "UNEXPECTED_ERROR"

# Resolver / integrity
DIGEST_MISMATCH = "DIGEST_MISMATCH"
COMMIT_INVALID = "COMMIT_INVALID"
PATH_ESCAPE = "PATH_ESCAPE"
ARTIFACT_DIGEST_MISMATCH = "ARTIFACT_DIGEST_MISMATCH"

ALL_CODES = frozenset(
    {
        MISSING_COLLECT_ARTIFACT,
        COLLECT_SCHEMA_MISMATCH,
        INVALID_COLLECT_PAYLOAD,
        NO_USABLE_MEMBER_SUMMARIES,
        DUPLICATE_ORDER_INDEX,
        LLM_CONFIGURATION,
        LLM_DISABLED,
        SYNTHESIS_DISABLED,
        SYNTHESIS_LOCK_TIMEOUT,
        PROMPT_BUDGET,
        SUMMARY_OVERSIZED,
        LLM_UNAVAILABLE,
        LLM_INVALID_RESPONSE,
        MAX_SPEAKERS,
        CANCELLED,
        UNEXPECTED_ERROR,
        DIGEST_MISMATCH,
        COMMIT_INVALID,
        PATH_ESCAPE,
        ARTIFACT_DIGEST_MISMATCH,
    }
)
